name: DSCT
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - torch>=1.7.1
  - numpy==1.23.4
  - pandas>=2.0.3
  - scanpy>=1.9.4
  - anndata>=0.9.2
  - pip
  - pip:
    - diopy>=0.5.5
    - cosg>=1.0.1
